---
title: Santa detector
hero_image: images/banner.png
description: Create a Scratch program to set off an alarm when Santa sneaks into
  your room
original_url: https://raspberrypi.org/learning/santa-detector
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: rpi, physical computing, scratch
site_areas: ''
steps:
- title: Introduction
- title: What you will need
- title: PIR motion sensors
- title: Test your motion sensor
- title: Create your Santa sprite
- title: Detecting Santa
- title: Set up the detector in your room!
- title: "Challenge: adding more actions"


